// Device Tree Source (DTS) Generator
// Converts application state into properly formatted DTS code
import { getQuirks, ETHERNET_DB } from './db.js';

/**
 * Format hex values safely to prevent 0x0x duplication
 * @param {string|number} value - Hex value as string or number
 * @returns {string} - Properly formatted hex string with 0x prefix
 */
function formatHex(value) {
  // If it's a number, convert to hex string
  if (typeof value === 'number') return `0x${value.toString(16)}`;
  
  // If it's a string, ensure it starts with 0x but isn't duplicated
  if (typeof value === 'string') {
    const clean = value.replace(/^0x/i, ''); // Remove existing 0x prefix (case insensitive)
    return `0x${clean}`;
  }
  return value;
}

/**
 * Generate complete DTS file from application state
 * @param {Object} state - { board, nodes: [{ name, enabled, phyAddr, pathway }] }
 * @returns {string} - Formatted DTS code
 */
export function generateDTS(state) {
  if (!state || !state.board || !state.nodes || state.nodes.length === 0) {
    return '// Select a board and configure ethernet nodes to generate DTS';
  }

  const enabledNodes = state.nodes.filter(n => n.enabled);
  if (enabledNodes.length === 0) {
    return '// Enable at least one ethernet node to generate DTS';
  }

  // Get board configuration with interfaces
  const boardKey = state.board.toLowerCase().replace(/[\s-]/g, '');
  const boardConfig = ETHERNET_DB.boards[boardKey];
  
  if (!boardConfig) {
    console.error('Board config not found for:', boardKey);
    return `// Error: Board configuration not found for ${state.board}`;
  }

  let dts = `/dts-v1/;\n\n`;
  dts += `/* Device Tree for ${state.board} */\n`;
  dts += `/* Auto-generated by Device Tree Architect */\n\n`;
  dts += `/ {\n`;
  dts += `\tmodel = "${state.board}";\n`;
  dts += `\tcompatible = "xlnx,zynqmp";\n\n`;
  dts += `\t/* Enabled Ethernet Nodes */\n`;

  enabledNodes.forEach((node, index) => {
    if (index > 0) dts += '\n';
    
    // Find matching interface config for this node
    let interfaceConfig = null;
    if (boardConfig.interfaces) {
      // Try to match by gem_node or axi_node
      interfaceConfig = boardConfig.interfaces.find(iface => 
        iface.gem_node === node.name || 
        iface.axi_node === node.name
      );
      
      // Debug: Log matching results
      console.log('🔍 Matching node:', node.name, 'Type:', node.nodeType);
      console.log('   Found interface:', interfaceConfig?.id, 'phy_mode:', interfaceConfig?.phy_mode);
      
      // If not found by exact match, try to match by interface ID
      if (!interfaceConfig && node.interfaceId) {
        interfaceConfig = boardConfig.interfaces.find(iface => iface.id === node.interfaceId);
        console.log('   📌 Matched by interfaceId:', interfaceConfig?.id);
      }
      
      if (!interfaceConfig) {
        console.warn('⚠️ No interface match found for node:', node.name, '- Using fallback');
      }
    }
    
    dts += formatEthernetNode(node, state, interfaceConfig, boardConfig.family);
  });

  dts += `};\n`;
  return dts;
}

/**
 * Get ethernet base address for node
 */
function getEthernetAddress(node) {
  // PS GEM addresses (ZynqMP)
  const gemAddresses = {
    'gem0': 'ff0b0000',
    'gem1': 'ff0c0000',
    'gem2': 'ff0d0000',
    'gem3': 'ff0e0000'
  };
  
  // PL AXI Ethernet addresses
  const plAddresses = {
    'axi_ethernet_0': 'a0000000',   // 1G AXI Ethernet
    'xxv_ethernet_0': 'a4000000'    // 10G/25G XXV Ethernet
  };
  
  return gemAddresses[node.name] || plAddresses[node.name] || node.address || 'ff0b0000';
}

/**
 * Format single ethernet node to DTS (Multi-Interface Version)
 * @param {object} node - Node object from state.nodes[]
 * @param {object} state - Full application state
 * @param {object} interfaceConfig - Interface configuration from board.interfaces[]
 * @param {string} family - Board family (zynqmp, versal, etc.)
 */
function formatEthernetNode(node, state, interfaceConfig = null, family = null) {
  // PS GEM nodes - Cadence Gigabit Ethernet MAC
  if (node.nodeType === 'PS') {
    const address = getEthernetAddress(node);
    const nodeName = `ethernet@${address}`;
    
    let result = `\t${nodeName} {\n`;
    result += `\t\tcompatible = "cdns,gem";\n`;
    result += `\t\tstatus = "okay";\n`;
    result += `\t\treg = <0x${address} 0x1000>;\n`;
    
    // Use interface config for phy-mode if available
    const phyMode = interfaceConfig?.phy_mode || node.phyMode || 'rgmii-id';
    result += `\t\tphy-mode = "${phyMode}";\n`;
    
    // Get version-specific quirks using interface configuration
    if (state && state.version && interfaceConfig) {
      const quirks = getQuirks(interfaceConfig, state.version, family);
      
      console.log('Generator - Interface:', interfaceConfig.id);
      console.log('Generator - Version:', state.version);
      console.log('Generator - Quirks:', quirks);
      
      // Add extra properties (reset GPIOs, Versal PTP, etc.)
      if (quirks.extra_props) {
        result += quirks.extra_props + '\n';
      }
    }
    
    // Add MDIO bus for PS GEM with external PHY
    const phyAddr = interfaceConfig?.phy_addr || node.phyAddr;
    if (phyAddr) {
      const phyAddrHex = formatHex(phyAddr);
      const phyAddrClean = phyAddrHex.replace(/^0x/, ''); // For node name
      const phyLabel = interfaceConfig?.phy_label || 'phy0';
      
      result += `\n\t\t/* MDIO Bus - ${interfaceConfig?.interface_type || node.pathway || 'MIO'} Path */\n`;
      result += `\t\tmdio {\n`;
      result += `\t\t\t#address-cells = <1>;\n`;
      result += `\t\t\t#size-cells = <0>;\n\n`;
      result += `\t\t\t${phyLabel}: ethernet-phy@${phyAddrClean} {\n`;
      
      // Use interface-specific compatible string if available
      const phyCompatible = interfaceConfig?.phy_compatible || 'ethernet-phy-ieee802.3-c22';
      result += `\t\t\t\tcompatible = "${phyCompatible}";\n`;
      result += `\t\t\t\treg = <${phyAddrHex}>;\n`;
      
      // Add PHY-specific quirks (TI delays, ADI delays, etc.)
      if (state && state.version && interfaceConfig) {
        const quirks = getQuirks(interfaceConfig, state.version, family);
        
        if (quirks.phy_delays) {
          result += quirks.phy_delays + '\n';
        }
      }
      
      result += `\t\t\t};\n`;
      result += `\t\t};\n`;
    }
    
    result += `\t};\n`;
    return result;
  }
  
  // PL AXI Ethernet nodes - Xilinx AXI Ethernet Subsystem
  else if (node.nodeType === 'PL') {
    const address = interfaceConfig?.axi_base_addr?.replace(/^0x/, '') || getEthernetAddress(node);
    
    // Determine if this is 10G based on phy_mode or node name
    const is10G = interfaceConfig?.phy_mode === '10gbase-r' || 
                  interfaceConfig?.phy_mode === '25gbase-r' ||
                  node.name.includes('10g') ||
                  node.name === 'xxv_ethernet_0';
    
    const nodeName = `axi_ethernet_${is10G ? '10g' : '1g'}@${address}`;
    
    // Determine compatible string based on phy_mode
    let compatible;
    if (is10G) {
      compatible = 'xlnx,xxv-ethernet-1.0';
    } else {
      compatible = 'xlnx,axi-ethernet-1.00.a';
    }
    
    // Prioritize node.phyMode (current state) over interfaceConfig.phy_mode (default from db)
    const phyMode = node.phyMode || interfaceConfig?.phy_mode || 'sgmii';
    
    console.log('🔧 PL Node Generation:', {
      nodeName: node.name,
      phyMode: phyMode,
      'interfaceConfig.phy_mode': interfaceConfig?.phy_mode,
      'node.phyMode': node.phyMode,
      isSerDes: (phyMode === '10gbase-r' || phyMode === '25gbase-r')
    });
    
    let result = `\t${nodeName} {\n`;
    result += `\t\tcompatible = "${compatible}";\n`;
    result += `\t\tstatus = "okay";\n`;
    result += `\t\treg = <0x${address} 0x40000>;\n`;
    result += `\t\tphy-mode = "${phyMode}";\n`;
    
    // Check if this is a SerDes-based interface (no external PHY)
    const isSerDes = phyMode === '10gbase-r' || phyMode === '25gbase-r';
    
    if (!isSerDes) {
      // For SGMII/RGMII/GMII - Generate MDIO bus and PHY handle
      const phyLabel = node.name === 'xxv_ethernet_0' ? 'phy_pl_10g' : 'phy_pl_1g';
      
      // Parse PHY address safely
      let phyAddr;
      if (interfaceConfig?.phy_addr) {
        phyAddr = interfaceConfig.phy_addr;
      } else if (typeof node.phyAddr === 'string') {
        phyAddr = parseInt(node.phyAddr.replace(/^0x/i, ''), 16) || 1;
      } else {
        phyAddr = node.phyAddr || 1;
      }
      
      result += `\t\tphy-handle = <&${phyLabel}>;\n`;
      
      // Add MDIO bus with labeled PHY
      result += `\n\t\t/* MDIO Bus - PL Ethernet PHY */\n`;
      result += `\t\tmdio {\n`;
      result += `\t\t\t#address-cells = <1>;\n`;
      result += `\t\t\t#size-cells = <0>;\n\n`;
      result += `\t\t\t${phyLabel}: ethernet-phy@${phyAddr} {\n`;
      result += `\t\t\t\tcompatible = "ethernet-phy-ieee802.3-c22";\n`;
      result += `\t\t\t\treg = <${phyAddr}>;\n`;
      result += `\t\t\t};\n`;
      result += `\t\t};\n`;
    } else {
      // For 10G/25G SerDes - No PHY, direct SFP+ connection
      result += `\t\t/* Direct SerDes connection - No external PHY */\n`;
    }
    
    result += `\t};\n`;
    return result;
  }
  
  // Fallback for unknown node types
  return `\t/* Unknown node type: ${node.name} */\n`;
}

/**
 * Generate Mermaid diagram from application state
 * @param {Object} state - Application state
 * @returns {string} - Mermaid diagram code
 */
export function renderMermaid(state) {
  if (!state || !state.board || !state.nodes || state.nodes.length === 0) {
    return `graph TD
    A[Select Board] --> B[Configure Ethernet]
    style A fill:#764ba2,stroke:#fff,color:#fff`;
  }

  const enabledNodes = state.nodes.filter(n => n.enabled);
  if (enabledNodes.length === 0) {
    return `graph TD
    Board[${state.board}] --> |No Nodes Enabled| Configure
    style Board fill:#764ba2,stroke:#fff,color:#fff`;
  }

  let mermaid = `graph LR\n`;
  mermaid += `    PS[Processing System<br/>${state.board}]\n`;

  enabledNodes.forEach((node, index) => {
    const nodeId = `GEM${index}`;
    const phyId = `PHY${index}`;
    const pathway = node.pathway || 'MIO';
    const color = getPathwayColor(pathway);
    const address = getEthernetAddress(node);
    
    // Display ethernet@address for PL nodes, keep gem name for PS
    const displayName = node.nodeType === 'PL' ? `ethernet@${address}` : node.name;
    
    // PL Ethernet uses AXI DMA/MCDMA, not direct PHY connection
    if (node.nodeType === 'PL') {
      const dmaType = node.name === 'xxv_ethernet_0' ? 'AXI MCDMA' : 'AXI DMA';
      const ethType = node.name === 'xxv_ethernet_0' ? 'PL Ethernet 10G/25G' : 'PL Ethernet 1G AXI';
      const bridgeId = `BRIDGE${index}`;
      
      mermaid += `    ${bridgeId}[${dmaType} - High-Speed Bridge]\n`;
      mermaid += `    ${nodeId}[${ethType} - ${displayName}]\n`;
      mermaid += `    ${phyId}[Ethernet PHY]\n`;
      mermaid += `    PS -->|AXI4| ${bridgeId}\n`;
      mermaid += `    ${bridgeId} -->|AXI4-Stream| ${nodeId}\n`;
      mermaid += `    ${nodeId} -->|${node.phyMode || 'sgmii'}| ${phyId}\n`;
      mermaid += `    style ${bridgeId} fill:#ff9800,stroke:#fff,color:#fff\n`;
      mermaid += `    style ${nodeId} fill:${color},stroke:#fff,color:#fff\n`;
    } else {
      // PS GEM - direct connection
      mermaid += `    ${nodeId}[${displayName}<br/>PHY: 0x${(node.phyAddr || 0).toString(16)}]\n`;
      mermaid += `    ${phyId}[Ethernet PHY]\n`;
      mermaid += `    PS -->|${pathway}| ${nodeId}\n`;
      mermaid += `    ${nodeId} -->|${node.phyMode || 'rgmii-id'}| ${phyId}\n`;
      mermaid += `    style ${nodeId} fill:${color},stroke:#fff,color:#fff\n`;
    }
  });

  mermaid += `    style PS fill:#764ba2,stroke:#fff,color:#fff\n`;
  return mermaid;
}

/**
 * Get color for pathway badge
 */
function getPathwayColor(pathway) {
  const colors = {
    'MIO': '#51cf66',
    'EMIO': '#f5576c',
    'GTR': '#3949ab'
  };
  return colors[pathway] || '#667eea';
}
